### ISSUE TITLE
cannot launch plot

### ISSUE THREAD

**Issue by anegrean** [louisnw01/lightweight-charts-python#11]
Hi, I just installed the package and ran this, which gave an error.

import yfinance as yf

df = yf.Ticker("aapl").history(start="2020-06-02", end="2020-06-07", interval="1d")
df = df.reset_index().rename(columns = {"Date": "time", "Open": "open", "High": "high", "Low": "low", "Close": "close", "Volume": "volume"})

import pandas as pd
from lightweight_charts import Chart

chart = Chart()

# Columns: | time | open | high | low | close | volume (if volume is enabled) |

chart.set(df)

chart.show(block=True)

Process Process-1:
Traceback (most recent call last):
  File "/home/adrian/miniconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/adrian/miniconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adrian/miniconda3/lib/python3.10/site-packages/lightweight_charts/chart.py", line 17, in __init__
    self.loop()
  File "/home/adrian/miniconda3/lib/python3.10/site-packages/lightweight_charts/chart.py", line 23, in loop
    webview.start(debug=self.debug) if arg == 'start' else getattr(self.webview, arg)()
  File "/home/adrian/miniconda3/lib/python3.10/site-packages/webview/__init__.py", line 132, in start
    guilib = initialize(gui)
  File "/home/adrian/miniconda3/lib/python3.10/site-packages/webview/guilib.py", line 92, in initialize
    if not try_import(guis):
  File "/home/adrian/miniconda3/lib/python3.10/site-packages/webview/guilib.py", line 62, in try_import
    if import_func():
  File "/home/adrian/miniconda3/lib/python3.10/site-packages/webview/guilib.py", line 16, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/adrian/miniconda3/lib/python3.10/site-packages/webview/platforms/gtk.py", line 41, in <module>
    webkit_ver = webkit.get_major_version(), webkit.get_minor_version(), webkit.get_micro_version()
gi.repository.GLib.GError: g-invoke-error-quark: Could not locate webkit_get_major_version: 'webkit_get_major_version': /lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18: undefined symbol: webkit_get_major_version (1)

** (ipykernel_launcher.py:81049): WARNING **: 00:18:13.758: Failed to load shared library 'libwebkit2gtk-4.0.so.37' referenced by the typelib: /lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: gst_codec_utils_caps_get_mime_codec

**Comment by anegrean** [comment]
Ju st wanted to say that this works fine:

import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

window = Gtk.Window(title="Test Window")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()

**Comment by louisnw01** [comment]
Hi! Are you encapsulating the Chart object code within a `__name__ == '__main__'` condition?

**Comment by anegrean** [comment]
Hi! I tried both encapsulating and in notebook. Same error.

**Comment by louisnw01** [comment]
The error message you got suggests that pywebview can't find GTK version 4.0; in your example script, do you get the same error message if you change this line: 
```python
gi.require_version("Gtk", "3.0")
```
To this:

```python
gi.require_version("Gtk", "4.0")
```
If so, it might be that you need to install gtk4 rather than gtk3.

**Comment by anegrean** [comment]
so doing gi.require_version("Gtk", "4.0") works
I do get an error later at window.connect("destroy", Gtk.main_quit)
'gi.repository.Gtk' object has no attribute 'main_quit'

But looking at the last bit of error from the initial post:

**Comment by louisnw01** [comment]
Hi,

Pywebview also supports QtWebEngine; the instructions for installation (on linux) can be found[ here](https://pywebview.flowrl.com/guide/installation.html#dependencies)
