### ISSUE TITLE
[BUG] re-opening graph from py script file or jupyter cell fails

### ISSUE THREAD

**Issue by scholz** [louisnw01/lightweight-charts-python#132]
### Expected Behavior

When rerunning the same cell (which created and showed a graph) in Jupyer or creating a new chart after the old one was closed the chart should open as before.

### Current Behaviour

Instead in jupyter it hangs (can only be solved for me by restarting the kernel) and in python it gives the following result:

```python
Traceback (most recent call last):
  File "F:\Documents\Firma\Projekte\Metirionic\code\crypto-experiments\crypto\.venv\lib\site-packages\webview\event.py", line 24, in execute
    value = func()
  File "F:\Documents\Firma\Projekte\Metirionic\code\crypto-experiments\crypto\.venv\lib\site-packages\lightweight_charts\chart.py", line 42, in <lambda>
    self.windows[-1].events.loaded += lambda: self.loop(self.loaded[len(self.windows)-1])
  File "F:\Documents\Firma\Projekte\Metirionic\code\crypto-experiments\crypto\.venv\lib\site-packages\lightweight_charts\chart.py", line 49, in loop
    self.create_window(*arg)
  File "F:\Documents\Firma\Projekte\Metirionic\code\crypto-experiments\crypto\.venv\lib\site-packages\lightweight_charts\chart.py", line 35, in create_window
    screen = webview.screens[screen]
  File "F:\Documents\Firma\Projekte\Metirionic\code\crypto-experiments\crypto\.venv\lib\site-packages\proxy_tools\__init__.py", line 133, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
  File "F:\Documents\Firma\Projekte\Metirionic\code\crypto-experiments\crypto\.venv\lib\site-packages\proxy_tools\__init__.py", line 62, in _get_current_object
    return self.__local()
  File "F:\Documents\Firma\Projekte\Metirionic\code\crypto-experiments\crypto\.venv\lib\site-packages\webview\__init__.py", line 382, in screens
    screens = guilib.get_screens()
  File "F:\Documents\Firma\Projekte\Metirionic\code\crypto-experiments\crypto\.venv\lib\site-packages\webview\platforms\winforms.py", line 789, in get_screens
    screens = [Screen(s.Bounds.Width, s.Bounds.Height, s.WorkingArea) for s in WinForms.Screen.AllScreens]
TypeError: 'PropertyObject' object is not iterable
``` 

Note that this seems to be connected with the init of guilib as it doesnt return the proper screens in the second init call.
Ie. here:
```python
@module_property
def screens() -> list[Screen]:
    guilib = initialize()
    screens = guilib.get_screens()
    return screens
``` 

screens is [(1920, 1080), (1920, 1080)] in the first call (I have three screens attached where one is disabled), while
screen is [pywebview] in the second call.

### Reproducible Example

```python
Use the example given in examples and simply clone the part in __main__ as follows:


import pandas as pd
from lightweight_charts import Chart


def get_bar_data(symbol, timeframe):
    if symbol not in ('AAPL', 'GOOGL', 'TSLA'):
        print(f'No data for "{symbol}"')
        return pd.DataFrame()
    return pd.read_csv(f'bar_data/{symbol}_{timeframe}.csv')


def on_search(chart, searched_string):  # Called when the user searches.
    new_data = get_bar_data(searched_string, chart.topbar['timeframe'].value)
    if new_data.empty:
        return
    chart.topbar['symbol'].set(searched_string)
    chart.set(new_data)


def on_timeframe_selection(chart):  # Called when the user changes the timeframe.
    new_data = get_bar_data(chart.topbar['symbol'].value, chart.topbar['timeframe'].value)
    if new_data.empty:
        return
    chart.set(new_data, True)


def on_horizontal_line_move(chart, line):
    print(f'Horizontal line moved to: {line.price}')


if __name__ == '__main__':
    chart = Chart(toolbox=True)
    chart.legend(True)

    chart.events.search += on_search

    chart.topbar.textbox('symbol', 'TSLA')
    chart.topbar.switcher('timeframe', ('1min', '5min', '30min'), default='5min',
                          func=on_timeframe_selection)

    df = get_bar_data('TSLA', '5min')
    chart.set(df)

    chart.horizontal_line(200, func=on_horizontal_line_move)

    chart.show(block=True)


    chart = Chart(toolbox=True)
    chart.legend(True)

    chart.events.search += on_search

    chart.topbar.textbox('symbol', 'TSLA')
    chart.topbar.switcher('timeframe', ('1min', '5min', '30min'), default='5min',
                          func=on_timeframe_selection)

    df = get_bar_data('TSLA', '5min')
    chart.set(df)

    chart.horizontal_line(200, func=on_horizontal_line_move)

    chart.show(block=True)
```

### Environment

```markdown
- OS: Win10
- Library: 10.0.17.6

Note tested also with 10.0.15 there it also didnt work giving a different error (also used the corresponding example). The version I am certain about that it worked - at least in Jupyter - was 1.0.13.4.
```

**Comment by louisnw01** [comment]
Hey @scholz,

The bug appears to be related to multiprocessing not being properly reinstanciated when opening a new window. Will aim to fix for the next update.

Louis

**Comment by scholz** [comment]
Hi @louisnw01,

thanks for your reply and considering a fix!

Since I wanted to work with the latest version of your very helpful lib -
I patched chart.py a little to make it work again. Maybe the code helps to fix it for the next release. I didnt do this as PR as I think it may not be completely correct wrt. other use-cases e.g. having multiple windows at the same time. If you prefer a PR let me know, but its just two lines.

Also I noticed that when calling `chart.show(block=False)` twice the example app doesnt terminate. But also I dont understand the use-case for block=False, is there one?

Here are the two changes (see comment above lines to see what was added) in chart.py which enable re-opening graphs in py script and jupyter cells:

```python

    async def show_async(self, block=False):
        self.show(block=False)
        if not block:
            asyncio.create_task(self.show_async(block=True))
            return
        try:
            from lightweight_charts import polygon
            [asyncio.create_task(self.polygon.async_set(*args)) for args in polygon._set_on_load]
            while 1:
                while self._emit_q.empty() and not self._exit.is_set():
                    await asyncio.sleep(0.05)
                if self._exit.is_set():
                    self._exit.clear()
                    self.is_alive = False
                    ## ADDED: call exit to terminate this graph
                    self.exit()
                    return
                elif not self._emit_q.empty():
                    func, args = parse_event_message(self.win, self._emit_q.get())
                    await func(*args) if asyncio.iscoroutinefunction(func) else func(*args)
                    continue
        except KeyboardInterrupt:
            return
   

    def exit(self):
        """
        Exits and destroys the chart window.\n
        """

        self._q.put((self._i, 'exit'))
        self._exit.wait() if self.win.loaded else None
        self._process.terminate()

        Chart._main_window_handlers = None
        Chart._window_num = 0
        Chart._q = mp.Queue()
        ## ADDED: clear event so next graph doesnt exit directly
        Chart._exit = mp.Event()
        self.is_alive = False

``` 

Best,
Markus

**Comment by louisnw01** [comment]
Fixed in the latest version.

Louis
