### ISSUE TITLE
Compatibility issues with Ubuntu 23 and python 3.11.  

### ISSUE THREAD

**Issue by DOABrownie** [louisnw01/lightweight-charts-python#204]
### Expected Behavior

When I follow the walkthrough it errors with the webview issue regarding needing QT or QML installation. 
linix, pi400, ubuntu23, python 3.11.6.

### Current Behaviour

Using PartTimeLarrys video as a guide mine does not render the first lightweight-chart code example due to issue

### Reproducible Example

```python
The first lightweight chart example
```

### Environment

```markdown
- OS:Ubuntu 23
- Library:
```

**Comment by DOABrownie** [comment]
Hay mate, thank you for getting back to me so quick,

I am running:
Ubuntu 23.10
Virtual env with:
    Python3 version 3.11.6
    pywebview 4.4.1
    pyside6 6.6.0
    lightweight-charts 1.0.18.5

I built this in my venv:
static>
    basic-chart.py
    ohlcv.csv
and am try the 1st stage of running the following basic-chart script:

import pandas as pd
from lightweight_charts import Chart


if __name__ == '__main__':

    chart = Chart()

    # Columns: time | open | high | low | close | volume
    df = pd.read_csv('static/ohlcv.csv')
    chart.set(df)

    chart.show(block=True)


which gives me this error:::
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/home/brownie/projects/Data_Plot_learn/venv/lib/python3.11/site-packages/webview/guilib.py", line 25, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/brownie/projects/Data_Plot_learn/venv/lib/python3.11/site-packages/webview/platforms/gtk.py", line 20, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "/home/brownie/projects/Data_Plot_learn/venv/lib/python3.11/site-packages/webview/guilib.py", line 37, in import_qt
    import webview.platforms.qt as guilib
  File "/home/brownie/projects/Data_Plot_learn/venv/lib/python3.11/site-packages/webview/platforms/qt.py", line 24, in <module>
    from qtpy import QtCore
ModuleNotFoundError: No module named 'qtpy'
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/brownie/projects/Data_Plot_learn/venv/lib/python3.11/site-packages/lightweight_charts/chart.py", line 31, in __init__
    webview.start(debug=debug)
  File "/home/brownie/projects/Data_Plot_learn/venv/lib/python3.11/site-packages/webview/__init__.py", line 155, in start
    guilib = initialize(gui)
             ^^^^^^^^^^^^^^^
  File "/home/brownie/projects/Data_Plot_learn/venv/lib/python3.11/site-packages/webview/guilib.py", line 109, in initialize
    raise WebViewException(
webview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.


:::::: At this point the console does not return to prompt and I cannot install any QT or GTQ packages.


I just want to follow through the walkthrough from basic to difficult to allow me to apply this knowledge to my project Swap Matrix V5.

Thanks for your support

Brownie
________________________________

**Comment by louisnw01** [comment]
Hey @DOABrownie,

Installation differs depending on your OS; check [this](https://pywebview.flowrl.com/guide/installation.html#dependencies) link.

Louis
