### ISSUE TITLE
why it throws the following error every now an then?

### ISSUE THREAD

**Issue by anilwarbhe** [louisnw01/lightweight-charts-python#207]
### Question

I keep receving the following error every now and then. Very frequently.

Traceback (most recent call last):
  File "/home/anil/pyprojects/trado/venv/lib/python3.11/site-packages/webview/platforms/gtk.py", line 473, in _callback
    value = webview.run_javascript_finish(task)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: WebKitJavascriptError: about:blank:12:2171: Error: Value is undefined (699)

**Comment by louisnw01** [comment]
Hey @anilwarbhe,

Have you narrowed down what part of your code causes this error?

Louis

**Comment by anilwarbhe** [comment]
> Hey @anilwarbhe,
> 
> Have you narrowed down what part of your code causes this error?
> 
> Louis

The complete error message is as follows:

Traceback (most recent call last):
  File "/home/anil/pyprojects/trado/venv/lib/python3.11/site-packages/webview/platforms/gtk.py", line 473, in _callback
    value = webview.run_javascript_finish(task)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: WebKitJavascriptError: about:blank:12:146829: Error: Cannot update oldest data, last time=[object Object], new time=[object Object] (699)

**Comment by louisnw01** [comment]
> > Hey @anilwarbhe,
> 
> > 
> 
> > Have you narrowed down what part of your code causes this error?
> 
> > 
> 
> > Louis
> 
> 
> 
> The complete error message is as follows:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/home/anil/pyprojects/trado/venv/lib/python3.11/site-packages/webview/platforms/gtk.py", line 473, in _callback
> 
>     value = webview.run_javascript_finish(task)
> 
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> gi.repository.GLib.GError: WebKitJavascriptError: about:blank:12:146829: Error: Cannot update oldest data, last time=[object Object], new time=[object Object] (699)
> 
> 

The error message means that you are updating the chart with data that occurs before the latest bar. 

Louis
