### ISSUE TITLE
[BUG]  PolygonChart error

### ISSUE THREAD

**Issue by neodino** [louisnw01/lightweight-charts-python#223]
### Expected Behavior

Start Polygon Chart.

### Current Behaviour

`2023-12-12 22:32:44.179 Python[35221:47225125] -[__NSCFBoolean length]: unrecognized selector sent to instance 0x1e7991eb8
Process Process-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/.venv/lib/python3.10/site-packages/lightweight_charts/chart.py", line 31, in __init__
    webview.start(debug=debug)
  File "/.venv/lib/python3.10/site-packages/webview/__init__.py", line 197, in start
    guilib.create_window(windows[0])
  File "/.venv/lib/python3.10/site-packages/webview/platforms/cocoa.py", line 1029, in create_window
    create()
  File "/.venv/lib/python3.10/site-packages/webview/platforms/cocoa.py", line 1025, in create
    browser = BrowserView(window)
  File "/.venv/lib/python3.10/site-packages/webview/platforms/cocoa.py", line 430, in __init__
    self.window.setTitle_(window.title)
ValueError: NSInvalidArgumentException - -[__NSCFBoolean length]: unrecognized selector sent to instance 0x1e7991eb8`

### Reproducible Example

```python
from lightweight_charts import PolygonChart

if __name__ == '__main__':
    chart = PolygonChart(
        api_key='xxxx',
        num_bars=200,
        limit=5000,
        live=True
    )
    chart.show(block=True)
```

### Environment

```markdown
- OS: 13.6.2
- Library: 1.0.18.8
```

**Comment by neodino** [comment]
Excellent lib by the way. Thanks for your effort.
