### ISSUE TITLE
[Exception has occurred: ValueError non convertible value 2023-12-11 07:30:00 with the unit 'ms'] 

### ISSUE THREAD

**Issue by blackHorz** [louisnw01/lightweight-charts-python#227]
### Expected Behavior

```
from lightweight_charts import Chart
import pandas as pd

if __name__ == '__main__':
    df = pd.read_csv('ohclv.csv')
    peaks = df.query('peak == peak')
    valleys = df.query('valley == valley')
    markers = []
    for index, row in peaks.iterrows():
        markers.append((row['date'], 'above', 'arrow_down', 'red', 'L'))
    for index, row in valleys.iterrows():
        markers.append((row['date'], 'down', 'arrow_up', 'green', 'S'))
    #Plot the signal
    chart = Chart()
    chart.set(df)
    for marker_item in sorted(markers, key=lambda x: x[0]):
        chart.marker(*marker_item)
    chart.show(block=True)
```

### Current Behaviour

This is how the elements of markers look like. 
('2023-12-11 11:45:00', 'above', 'arrow_down', 'red', 'L')

I am using Windows 10

### Reproducible Example

```python
Thats the error trace

Traceback (most recent call last):
  File "pandas\_libs\tslib.pyx", line 361, in pandas._libs.tslib.array_with_unit_to_datetime
ValueError: could not convert string to float: '2023-12-11 07:30:00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hbalu\anaconda3\lib\site-packages\lightweight_charts\abstract.py", line 263, in marker
    time = self._last_bar['time'] if not time else self._single_datetime_format(time)
  File "C:\Users\hbalu\anaconda3\lib\site-packages\lightweight_charts\abstract.py", line 213, in _single_datetime_format
    arg = pd.to_datetime(arg, unit='ms')
  File "C:\Users\hbalu\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py", line 1102, in to_datetime
    result = convert_listlike(np.array([arg]), format)[0]
  File "C:\Users\hbalu\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py", line 393, in _convert_listlike_datetimes
    return _to_datetime_with_unit(arg, unit, name, tz, errors)
  File "C:\Users\hbalu\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py", line 557, in _to_datetime_with_unit
    arr, tz_parsed = tslib.array_with_unit_to_datetime(arg, unit, errors=errors)
  File "pandas\_libs\tslib.pyx", line 364, in pandas._libs.tslib.array_with_unit_to_datetime
ValueError: non convertible value 2023-12-11 07:30:00 with the unit 'ms'
```

### Environment

```markdown
- OS: Windows 10
- Library: lightweight_charts
```

**Comment by louisnw01** [comment]
Hey @blackHorz,

Try converting the date column to a date time object first, with `pd.to_datetime`

Louis

**Comment by Roh-codeur** [comment]
for anyone else who reaches here: the below code fix for 
**examples/3_tick_data/tick_data.py**

```
import pandas as pd
from time import sleep
from lightweight_charts import Chart

if __name__ == '__main__':

    df1 = pd.read_csv('ohlc.csv')

    # Columns: time | price
    df2 = pd.read_csv('ticks.csv')
    df2["time"] = pd.to_datetime(df2["time"])
    chart = Chart()

    chart.set(df1)

    chart.show()

    for i, tick in df2.iterrows():
        chart.update_from_tick(tick)
        sleep(0.03)

```
