### ISSUE TITLE
[BUG]  Markers stop working after version 1.0.18.5; issue with datetime conversion

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#228]
### Expected Behavior

Marker should render, I have a test harness that working for all version 1.0.18.5 and earlier 
From from that version onward, always throws as exception on the conversion

This is version 1.0.18.5
![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/fb90181a-1837-4a91-ad6b-c4cd3db6fd9b)

### Current Behaviour

```
Markers: ['2023-03-31T00:00:00.000000000' '2023-03-17T00:00:00.000000000'
 '2023-03-03T00:00:00.000000000']
Traceback (most recent call last):
  File "C:\Users\karun\Documents\PycharmProjects\light_chart_version_verifiy\markers.py", line 25, in <module>
    chart.marker(point.astype(dt.datetime), position='above')
  File "C:\Users\karun\Documents\PycharmProjects\light_chart_version_verifiy\venv\Lib\site-packages\lightweight_charts\abstract.py", line 263, in marker
    time = self._last_bar['time'] if not time else self._single_datetime_format(time)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\karun\Documents\PycharmProjects\light_chart_version_verifiy\venv\Lib\site-packages\lightweight_charts\abstract.py", line 213, in _single_datetime_format
    arg = pd.to_datetime(arg, unit='ms')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\karun\Documents\PycharmProjects\light_chart_version_verifiy\venv\Lib\site-packages\pandas\core\tools\datetimes.py", line 1146, in to_datetime
    result = convert_listlike(np.array([arg]), format)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\karun\Documents\PycharmProjects\light_chart_version_verifiy\venv\Lib\site-packages\pandas\core\tools\datetimes.py", line 462, in _convert_listlike_datetimes
    return _to_datetime_with_unit(arg, unit, name, utc, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\karun\Documents\PycharmProjects\light_chart_version_verifiy\venv\Lib\site-packages\pandas\core\tools\datetimes.py", line 545, in _to_datetime_with_unit
    arr = astype_overflowsafe(arr, np.dtype("M8[ns]"), copy=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "np_datetime.pyx", line 319, in pandas._libs.tslibs.np_datetime.astype_overflowsafe
  File "np_datetime.pyx", line 413, in pandas._libs.tslibs.np_datetime.astype_overflowsafe
  File "np_datetime.pyx", line 400, in pandas._libs.tslibs.np_datetime.astype_overflowsafe
  File "np_datetime.pyx", line 231, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 53246047-07-26 00:00:00
```

### Reproducible Example

```python
import pandas as pd
import datetime as dt
from lightweight_charts import Chart
import importlib.metadata

lib_version = importlib.metadata.version('lightweight_charts')

if __name__ == '__main__':

    chart = Chart(inner_height=1)
    chart.topbar.textbox('version', initial_text=f'lightweight_chart=={lib_version}')
    chart.legend(visible=True)

    df = pd.read_csv('ohlcv.csv')
    df.date = pd.to_datetime(df.date, format='%Y-%m-%d')
    marker_locs = df.iloc[[-10,-20,-30]].date.values
    print(f'Markers: {marker_locs}')

    df = df['date open high low close volume'.split()]
    df = df.set_index('date')

    for point in marker_locs:
        chart.marker(point.astype(dt.datetime), position='above')

    df = df.dropna()
    chart.set(df)

    chart.show(block=True)
```

### Environment

```markdown
- OS:Win10
- Library:1.0.18.8
```

**Comment by karunkrishna** [comment]
Note these lines, I am converting to pd.to_datetime

    df.date = pd.to_datetime(df.date, format='%Y-%m-%d')


"M8[ns]" 

Were you able to run the sample code between those two versions on your local
What version of Numpy and Pandas are you using. 
Wondering if it is a dependency package that has changed....

**Comment by louisnw01** [comment]
Yep, I have changed the default timestamp to be milliseconds rather than nanoseconds. So you'd just need to add in this line:

`chart.marker(point.astype(dt.datetime)/1000000, position='above')`

Louis
