### ISSUE TITLE
JavaScript error when enabling toolbox

### ISSUE THREAD

**Issue by 234324** [louisnw01/lightweight-charts-python#333]
### Expected Behavior

Chart displays as expected when created as Chart(), but trying to enable the toolbox with Chart(toolbox=True) throws an error.

### Current Behaviour

Running example code gives following error.

```bash
[pywebview] Using Cocoa
[pywebview] {'name': 'SyntaxError', 'message': "Unexpected token '='. Expected an opening '(' before a method's parameter list.", 'line': 4, 'column': 33, 'sourceURL': 'about:blank', 'stack': 'eval@[native code]\nglobal code@about:blank:4:33'}
Traceback (most recent call last):
  File "[...]/venv/lib/python3.12/site-packages/webview/event.py", line 41, in execute
    value = func()
            ^^^^^^
  File "[...]/venv/lib/python3.12/site-packages/lightweight_charts/chart.py", line 46, in <lambda>
    self.windows[-1].events.loaded += lambda: self.loop(self.loaded[len(self.windows)-1])
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/venv/lib/python3.12/site-packages/lightweight_charts/chart.py", line 63, in loop
    self.windows[i].evaluate_js(arg)
  File "[...]/venv/lib/python3.12/site-packages/webview/window.py", line 50, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/venv/lib/python3.12/site-packages/webview/window.py", line 444, in evaluate_js
    raise JavascriptException(result)
webview.errors.JavascriptException: {'name': 'SyntaxError', 'message': "Unexpected token '='. Expected an opening '(' before a method's parameter list.", 'line': 4, 'column': 33, 'sourceURL': 'about:blank', 'stack': 'eval@[native code]\nglobal code@about:blank:4:33'}
```

### Reproducible Example

```python
import pandas as pd
from lightweight_charts import Chart

if __name__ == '__main__':
    chart = Chart(toolbox=True, debug=True)

    data = pd.DataFrame({
        'time': [pd.Timestamp('2024-04-08'), pd.Timestamp('2024-04-09'), pd.Timestamp('2024-04-10')], 
        'open': [887.0, 874.42, 839.26], 
        'high': [888.3, 876.35, 874.0],
        'low': [867.32, 830.22, 837.09], 
        'close': [871.33, 853.54, 870.39], 
        'volume': [28322000.0, 50350935.0, 43179153.0],
    })

    chart.set(data)
    chart.show(block=True)
```

### Environment

```markdown
- OS: macOS 10.15.7
- Library: 1.0.20
- Python: 3.12.0
```

**Comment by Iss-in** [comment]
getting  similar issue , on enabling toolbox, a black window is being created, and cpu usage is spiking to max

- OS: Arch
- Library: git version of main branch
- Python: 3.12.3

**Comment by surajrimal07** [comment]
getting similar issue here too, Windows 11, Main branch and python 3.11.0

**Comment by louisnw01** [comment]
Hotfix published now; sorry for the wait!
