### ISSUE TITLE
Dependency list for ARCH linux

### ISSUE THREAD

**Issue by armeya25** [louisnw01/lightweight-charts-python#334]
### Question

Can to give me dependency list for lightweight charts for ARCH linux,
I can't get it work now 😭

Webveiw gives error:
You must have either QT or GTK with Python extensions installed in order to use pywebview

After installating extensions chart shows but didn't draw candles only black window

**Comment by armeya25** [comment]
webkit2gtk seem to conflict with qtwebengine

**Comment by armeya25** [comment]
File "/home/armeya/documents/gtf main/.venv/lib/python3.11/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit2 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/armeya/documents/gtf main/.venv/lib/python3.11/site-packages/webview/guilib.py", line 37, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/armeya/documents/gtf main/.venv/lib/python3.11/site-packages/webview/platforms/gtk.py", line 31, in <module>
    gi.require_version('WebKit2', '4.0')
  File "/home/armeya/documents/gtf main/.venv/lib/python3.11/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit2 not available
<PyQt5.QtWebEngineWidgets.QWebEngineProfile object at 0x7b745299acb0>
js: Uncaught TypeError: Cannot read property 'options' of undefined
js: Uncaught TypeError: Cannot read property 'options' of undefined

this is error if webkit2gtk is not installed on arch linux
if  webkit2gtk  installed then it shows blank window

**Comment by armeya25** [comment]
Seems like webkit2gtk / pygobject doesnt work on I3WM

**Comment by armeya25** [comment]
export WEBKIT_DISABLE_COMPOSITING_MODE="1"

After this it works fine with gtk
