### ISSUE TITLE
[BUG] Cann't take screenshot (pyqt5)

### ISSUE THREAD

**Issue by Tapanhaz** [louisnw01/lightweight-charts-python#354]
### Expected Behavior

It gives error :

### Current Behaviour

Traceback (most recent call last):
  File "E:\Works\Project VI\charting\test_screenshot.py", line 27, in take_screenshot
    img = self.chart.screenshot()
  File "D:\Py_Env\v311\lib\site-packages\lightweight_charts\abstract.py", line 1020, in screenshot
    serial_data = self.win._return_q.get()
AttributeError: 'Window' object has no attribute '_return_q'

### Reproducible Example

```python
import pandas as pd
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget, QPushButton
from lightweight_charts.widgets import QtChart

class ChartWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setup_ui()

    def setup_ui(self):
        self.setWindowTitle("Chart Window")
        self.resize(800, 500)

        self.layout = QVBoxLayout()
        self.central_widget = QWidget()
        self.central_widget.setLayout(self.layout)
        self.setCentralWidget(self.central_widget)

        self.chart = QtChart(self.central_widget)
        self.layout.addWidget(self.chart.get_webview())

        self.screenshot_button = QPushButton("Screenshot")
        self.screenshot_button.clicked.connect(self.take_screenshot)
        self.layout.addWidget(self.screenshot_button)

    def take_screenshot(self):
        img = self.chart.screenshot()
        with open('screenshot.png', 'wb') as f:
            f.write(img)

if __name__ == "__main__":
    data = [
        {'time': '2019-04-01', 'open': 100.0, 'high': 100.0, 'low': 95.3, 'close': 95.3}, 
        {'time': '2019-04-02', 'open': 95.3, 'high': 98.49, 'low': 95.3, 'close': 98.49}, 
        {'time': '2019-04-03', 'open': 98.49, 'high': 101.03, 'low': 98.49, 'close': 101.03}, 
        {'time': '2019-04-04', 'open': 101.03, 'high': 101.03, 'low': 98.05, 'close': 98.05}, 
        {'time': '2019-04-05', 'open': 98.05, 'high': 98.99, 'low': 98.05, 'close': 98.99}, 
        {'time': '2019-04-06', 'open': 98.99, 'high': 98.99, 'low': 97.27, 'close': 97.27}, 
        {'time': '2019-04-07', 'open':97.27, 'high': 97.71, 'low': 97.27, 'close': 97.71}, 
        {'time': '2019-04-08', 'open': 97.71, 'high': 99.38, 'low': 97.71, 'close': 99.38}, 
        {'time': '2019-04-09', 'open': 99.38, 'high': 99.38, 'low': 97.57, 'close': 97.57}, 
        {'time': '2019-04-10', 'open': 97.57, 'high': 97.57, 'low': 97.11, 'close': 97.11}]

    df = pd.DataFrame().from_records(data)
    df.set_index("time", inplace=True)

    app = QApplication([])
    window = ChartWindow()
    window.chart.set(df)
    window.show()
    app.exec_()
```

### Environment

```markdown
- OS:Windows 10
- Library:1.0.21
```

**Comment by louisnw01** [comment]
the screenshot method only works with the normal `Chart` object.
