### ISSUE TITLE
[BUG] 2.0 release crashes during line deletions

### ISSUE THREAD

**Issue by pranavladkat** [louisnw01/lightweight-charts-python#388]
### Expected Behavior

see current behavior section

### Current Behaviour

Thanks for the update with 2.0 release! It appears that there is some issue while deleting lines and the code crashes with an error something like mentioned below. 

```
Exception in thread Thread-2 (loop):
Traceback (most recent call last):
  File "/<>/site-packages/lightweight_charts/chart.py", line 89, in loop
    window.evaluate_js(arg)
  File "/<>/site-packages/webview/window.py", line 50, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<>/site-packages/webview/window.py", line 455, in evaluate_js
    raise JavascriptException(result)
webview.errors.JavascriptException: {'name': 'TypeError', 'message': "undefined is not an object (evaluating 's.value')", 'line': 1, 'column': 5433, 'sourceURL': 'http://127.0.0.1:59520/bundle.js', 'stack': '@http://127.0.0.1:59520/bundle.js:1:5433\nforEach@[native code]\nlegendHandler@http://127.0.0.1:59520/bundle.js:1:5133\nforEach@[native code]\nm@http://127.0.0.1:59520/lightweight-charts.js:7:6624\n@http://127.0.0.1:59520/lightweight-charts.js:7:157504\nforEach@[native code]\nm@http://127.0.0.1:59520/lightweight-charts.js:7:6624\n$m@http://127.0.0.1:59520/lightweight-charts.js:7:143503\nforEach@[native code]\nm@http://127.0.0.1:59520/lightweight-charts.js:7:6624\nQc@http://127.0.0.1:59520/lightweight-charts.js:7:86290\nql@http://127.0.0.1:59520/lightweight-charts.js:7:86569\nJ@http://127.0.0.1:59520/lightweight-charts.js:7:53796\nforEach@[native code]\nfw@http://127.0.0.1:59520/lightweight-charts.js:7:159535\nJb@http://127.0.0.1:59520/lightweight-charts.js:7:158557\nsetData@http://127.0.0.1:59520/lightweight-charts.js:7:153441\neval code@\neval@[native code]\nglobal code@http://127.0.0.1:59520/test.html:4:33'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/<>/site-packages/lightweight_charts/chart.py", line 94, in loop
    raise JavascriptException(f"\n\nscript -> '{arg}',\nerror -> {msg['name']}[{msg['line']}:{msg['column']}]\n{msg['message']}")
webview.errors.JavascriptException: 

script -> '
            window.pvnanbpj.chart.removeSeries(window.odjxlhwq.series)
            window.pvnanbpj.legend.lines.forEach(line => {
                if (line.line === window.odjxlhwq) window.pvnanbpj.legend.div.removeChild(line.row)
            })
            delete window.odjxlhwq
        ',
error -> TypeError[1:5433]
undefined is not an object (evaluating 's.value')
...
```

### Reproducible Example

```python
To reproduce the code, simply load different symbols (by typing) and it should crash with less than 5 symbols (e.g. SPY, QQQ, TSLA, AMZN, META, etc.).



import datetime as dt
import yfinance as yf
from lightweight_charts import Chart
import numpy as np
import pandas as pd

lines = []


def get_bar_data(symbol, timeframe):
    global lines
    if timeframe in ('1m', '5m', '30m'):
        days = 6 if timeframe == '1m' else 59
        start_date = dt.datetime.now()-dt.timedelta(days=days)
    else:
        start_date = None

    # if commented, no errors occur
    for line in lines:
        line.delete()
    lines.clear()

    chart.spinner(True)
    data = yf.download(symbol, start_date, interval=timeframe)
    chart.spinner(False)

    if data.empty:
        return False
    chart.set(data)

    # create lines
    high = data['High'].max()
    low = data['Low'].min()
    arr = np.linspace(low, high, 10).tolist()
    for price in arr:
        name = f"line_{price}"
        line = chart.create_line(name, price_line=False, price_label=False)
        line_df = pd.DataFrame(index=data.index)
        line_df[name] = price
        line.set(line_df)
        lines.append(line)

    return True


def on_search(chart, searched_string):
    if get_bar_data(searched_string, chart.topbar['timeframe'].value):
        chart.topbar['symbol'].set(searched_string)


def on_timeframe_selection(chart):
    get_bar_data(chart.topbar['symbol'].value, chart.topbar['timeframe'].value)


if __name__ == '__main__':
    chart = Chart(toolbox=True, debug=False)
    chart.legend(True)
    chart.events.search += on_search
    chart.topbar.textbox('symbol', 'AMD')
    chart.topbar.switcher(
        'timeframe',
        ('1m', '5m', '30m', '1d', '1wk'),
        default='5m',
        func=on_timeframe_selection
    )

    chart.show(block=True)


```
```


### Environment

```markdown
- OS:  Ubuntu
- Library: 2.0
```

**Comment by ctrlji** [comment]
This issue still persists

**Comment by anilwarbhe** [comment]
I am facing the same issue in latest version 2.1 when I change it to 2.0.1 it works. I really appreciate you help to fix it up.
