### ISSUE TITLE
Setting multiple lines in a loop [BUG]

### ISSUE THREAD

**Issue by Zartexo** [louisnw01/lightweight-charts-python#414]
### Expected Behavior

The lines should be drawn normally without error.

### Current Behaviour

I upgraded the library from 1.0.18.8 and my charts don't load as exptected anymore.
The below code example shows the problem. If I run the code and press "addLines" Button quickly after chart is shown I get the following error: 

```
Exception in thread Thread-2 (loop):
Traceback (most recent call last):
  File "C:\Users\Zartexo\Documents\Zartexo\PyVenv\lib\site-packages\lightweight_charts\chart.py", line 89, in loop
    window.evaluate_js(arg)
  File "C:\Users\Zartexo\Documents\Zartexo\PyVenv\lib\site-packages\webview\window.py", line 50, in wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\Zartexo\Documents\Zartexo\PyVenv\lib\site-packages\webview\window.py", line 455, in evaluate_js
    raise JavascriptException(result)
webview.errors.JavascriptException: {'name': 'Error', 'stack': 'Error: Value is null\n    at f (http://127.0.0.1:19722/lightweight-charts.js:7:2213)\n    at An.td (http://127.0.0.1:19722/lightweight-charts.js:7:86360)\n    at Pe.setCrosshairPosition (http://127.0.0.1:19722/lightweight-charts.js:7:159252)\n    at s (http://127.0.0.1:19722/bundle.js:1:41778)\n    at Object.d [as o] (http://127.0.0.1:19722/bundle.js:1:42111)\n    at http://127.0.0.1:19722/lightweight-charts.js:7:6631\n    at Array.forEach (<anonymous>)\n    at k.m (http://127.0.0.1:19722/lightweight-charts.js:7:6617)\n    at Object.o (http://127.0.0.1:19722/lightweight-charts.js:7:157503)\n    at http://127.0.0.1:19722/lightweight-charts.js:7:6631', 'message': 'Value is null'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zartexo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Zartexo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Zartexo\Documents\Zartexo\PyVenv\lib\site-packages\lightweight_charts\chart.py", line 94, in loop
    raise JavascriptException(f"\n\nscript -> '{arg}',\nerror -> {msg['name']}[{msg['line']}:{msg['column']}]\n{msg['message']}")
KeyError: 'line'
```

Also only the first or 2-3 lines get drawn.
In this code example I could just wait more time before pressing buttons but in my program I get the same error on different occasions which seems to be introduced with v 2.0 or 2.0.1. I also tried to use chart.bulk_run which performs worse:

```
def addLines(chart):
  with chart.bulk_run:
        for i in chart.lines():
            i.set(df2)
        
def removeLines(chart):
  with chart.bulk_run:
        df = pd.DataFrame
        for i in chart.lines():
            i.set(df)
```

### Reproducible Example

```python
import pandas as pd
from lightweight_charts import Chart

def addLines(chart):
    for i in chart.lines():
        i.set(df2)
        
def removeLines(chart):
    df = pd.DataFrame
    for i in chart.lines():
        i.set(df)

if __name__ == '__main__':
    chart = Chart(inner_width=1, inner_height=0.8)
    chart2 = chart.create_subchart(sync=True, position='bottom', width=1, height=0.2)
    chart.legend(visible=True, ohlc=True, lines=True, percent=False)
    
    LineElements = ['test1', 'test2', 'test3', 'test4', 'test5', 'test6', 'test7', 'test8', 'test9']
    chart.create_line(color='rgba(105, 226, 182, 0.8)', price_line=False, price_label=False, name=LineElements[0])
    chart.create_line(color='rgba(226, 105, 182, 0.8)', price_line=False, price_label=False, name=LineElements[1])
    chart.create_line(color='rgba(169, 167,  22, 0.8)', price_line=False, price_label=False, name=LineElements[2])
    chart.create_line(color='rgba(101,  40, 156, 0.8)', price_line=False, price_label=False, name=LineElements[3])
    chart.create_line(color='rgba(152, 237, 162, 0.8)', price_line=False, price_label=False, name=LineElements[4])
    chart.create_line(color='rgba(237, 152, 162, 0.8)', price_line=False, price_label=False, name=LineElements[5])
    chart.create_line(color='rgba(132, 155, 249, 0.8)', price_line=False, price_label=False, name=LineElements[6])
    chart.create_line(color='rgba(132, 155, 249, 0.8)', price_line=False, price_label=False, name=LineElements[7])
    chart.create_line(color='rgba(132, 155, 249, 0.8)', price_line=False, price_label=False, name=LineElements[8])

    chart.watermark('1')

    
    chart.topbar.button('addLines', 'addLines', func=addLines)
    chart.topbar.button('removeLines', 'removeLines', func=removeLines)

    df = pd.read_csv("ohlcv.csv")
    df2 = df[['date']]
    df2['test1'] = df['close'] * 1
    df2['test2'] = df['close'] * 2
    df2['test3'] = df['close'] * 3
    df2['test4'] = df['close'] * 4
    df2['test5'] = df['close'] * -1
    df2['test6'] = df['close'] * -2
    df2['test7'] = df['close'] * -3
    df2['test8'] = df['close'] * -4
    df2['test9'] = df['close'] * 0.5
    
    chart.set(df)
    
    chart.show(block=True)
```

### Environment

```markdown
- OS: Windows 10 Pro Version 10.0.19045 Build 19045
- Library: 2.0.1
```

**Comment by louisnw01** [comment]
Unable to repro

**Comment by algotrading-py** [comment]
Same error occured while trying to delete a line. Reproducible Example

Minimal reproducable example:

```
import time

import pandas as pd
from lightweight_charts import Chart


def calculate_sma(df, period: int = 50):
    return pd.DataFrame(
        {"time": df["date"], f"SMA {period}": df["close"].rolling(window=period).mean()}
    ).dropna()


if __name__ == "__main__":
    chart = Chart()
    line = chart.create_line(name="SMA 20")

    df = pd.read_csv("ohlcv.csv")
    sma_df = calculate_sma(df, period=20)

    chart.set(df)
    line.set(sma_df)
    time.sleep(5)

    line.delete()

    chart.show(block=True)
```

Error

```
Exception in thread Thread-2 (loop):
Traceback (most recent call last):
  File "C:\Users\serge\.conda\envs\bt24\Lib\site-packages\lightweight_charts\chart.py", line 89, in loop
    window.evaluate_js(arg)
  File "C:\Users\serge\.conda\envs\bt24\Lib\site-packages\webview\window.py", line 50, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\serge\.conda\envs\bt24\Lib\site-packages\webview\window.py", line 455, in evaluate_js
    raise JavascriptException(result)
webview.errors.JavascriptException: {'name': 'NotFoundError', 'stack': "Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.\n    at eval (eval at <anonymous> (:4:29), <anonymous>:56598:44)\n    at <anonymous>:4:29"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\serge\.conda\envs\bt24\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\serge\.conda\envs\bt24\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\serge\.conda\envs\bt24\Lib\site-packages\lightweight_charts\chart.py", line 94, in loop
    raise JavascriptException(f"\n\nscript -> '{arg}',\nerror -> {msg['name']}[{msg['line']}:{msg['column']}]\n{msg['message']}")
                                                                                ~~~^^^^^^^^
KeyError: 'line'
```

Enviroment configuration:

```
pip list
Package                     Version
--------------------------- -----------
anyio                       4.4.0
asttokens                   2.4.1
backtrader                  1.9.78.123
bottle                      0.13.1
certifi                     2024.8.30
cffi                        1.17.1
clr-loader                  0.2.6
colorama                    0.4.6
comm                        0.2.2
contourpy                   1.3.0
cramjam                     2.8.3
cycler                      0.12.1
debugpy                     1.6.7
decorator                   5.1.1
dynaconf                    3.2.6
exceptiongroup              1.2.2
executing                   2.1.0
fastparquet                 2024.5.0
fonttools                   4.53.1
fsspec                      2024.9.0
h11                         0.14.0
httpcore                    1.0.5
httpx                       0.27.2
idna                        3.10
importlib_metadata          8.5.0
ipykernel                   6.29.5
ipython                     8.27.0
jedi                        0.19.1
jupyter_client              8.6.2
jupyter_core                5.7.2
keyboard                    0.13.5
kiwisolver                  1.4.7
lightweight-charts          2.1
matplotlib                  3.9.2
matplotlib-inline           0.1.7
moexalgo                    2.1.1
nest_asyncio                1.6.0
numpy                       1.26.4
packaging                   24.1
pandas                      2.2.3
parso                       0.8.4
pickleshare                 0.7.5
pillow                      10.4.0
pip                         24.2
platformdirs                4.3.3
prompt_toolkit              3.0.47
proxy_tools                 0.1.0
psutil                      5.9.0
pure_eval                   0.2.3
pyarrow                     17.0.0
pycparser                   2.22
Pygments                    2.18.0
pyparsing                   3.1.4
PyQt6-Qt6                   6.7.2
PyQt6_sip                   13.8.0
PyQt6-WebEngine-Qt6         6.7.2
PyQt6-WebEngineSubwheel-Qt6 6.7.2
python-dateutil             2.9.0.post0
python-telegram-bot         21.5
pythonnet                   3.0.4
pytz                        2024.2
pywebview                   5.2
pywin32                     305.1
pyzmq                       25.1.2
setuptools                  72.1.0
six                         1.16.0
sniffio                     1.3.1
stack-data                  0.6.2
TA-Lib                      0.4.32
tornado                     6.4.1
traitlets                   5.14.3
typing_extensions           4.12.2
tzdata                      2024.2
wcwidth                     0.2.13
wheel                       0.44.0
zipp                        3.20.2
```

**Comment by algotrading-py** [comment]
Workaround is to change 

```
if ({self.id}legendItem) {{
 {self._chart.id}.legend.div.removeChild({self.id}legendItem.row)
}}
```
with
```
if ({self.id}legendItem) {{
 {self.id}legendItem.row.remove();
}}
```
in https://github.com/louisnw01/lightweight-charts-python/blob/052d778beda66f569175cbe6774aba5d3e3b1dea/lightweight_charts/abstract.py#L478-L480
