### ISSUE TITLE
[BUG] chart.set() does not work on the first chart when 2 charts are synced

### ISSUE THREAD

**Issue by algotrading-py** [louisnw01/lightweight-charts-python#475]
### Expected Behavior

No error

### Current Behaviour

```
  File "C:\Users\serge\.conda\envs\bt24\Lib\site-packages\webview\window.py", line 455, in evaluate_js
    raise JavascriptException(result)
webview.errors.JavascriptException: {'name': 'Error', 'stack': 'Error: Value is null\n    at f (http://127.0.0.1:34436/lightweight-charts.js:7:2213)\n    at An.td (http://127.0.0.1:34436/lightweight-charts.js:7:86360)\n    at Pe.setCrosshairPosition (http://127.0.0.1:34436/lightweight-charts.js:7:159252)\n    at s (http://127.0.0.1:34436/bundle.js:1:42077)\n    at Object.d [as o] (http://127.0.0.1:34436/bundle.js:1:42410)\n    at http://127.0.0.1:34436/lightweight-charts.js:7:6631\n    at Array.forEach (<anonymous>)\n    at k.m (http://127.0.0.1:34436/lightweight-charts.js:7:6617)\n    at Object.o (http://127.0.0.1:34436/lightweight-charts.js:7:157503)\n    at http://127.0.0.1:34436/lightweight-charts.js:7:6631', 'message': 'Value is null'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\serge\.conda\envs\bt24\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\serge\.conda\envs\bt24\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\serge\.conda\envs\bt24\Lib\site-packages\lightweight_charts\chart.py", line 94, in loop
    raise JavascriptException(f"\n\nscript -> '{arg}',\nerror -> {msg['name']}[{msg['line']}:{msg['column']}]\n{msg['message']}")
                                                                                ~~~^^^^^^^^
KeyError: 'line'

```
![image](https://github.com/user-attachments/assets/3cec5b49-0b16-4238-9d63-da0d4501868f)

### Reproducible Example

```python
# it's not full, just part

# определяем графики
    chart = Chart(
        width=1500,
        height=600,
        inner_width=w1,
        inner_height=h1,
        toolbox=True,
        debug=True,
    )
    set_chart_style(style, chart)
    if mysizecharts in [2, 3]:
        chart2 = chart.create_subchart(width=w1, height=h2, sync=True)
        chart2.time_scale(visible=False)
        set_chart_style(style, chart2)
    if mysizecharts == 3:
        chart3 = chart.create_subchart(width=w1, height=h3, sync=False)
        chart3.time_scale(visible=False)
        set_chart_style(style, chart3)
```

### Environment

```markdown
Does not matter. Latest version of the library.
```

**Comment by behajakum** [comment]
I am also facing the same issue. Could it be fixed?

**Comment by NikolayNelubov** [comment]
Check if you have the latest versions of providers renderer installed for your platform. Here is a link for more information --> [Web engine](https://pywebview.flowrl.com/guide/web_engine.html) For Windows platform, you need installed above >.NET Framework 4.6.2 and Edge WebView2 Runtime.
