### ISSUE TITLE
About vertical_span ..

### ISSUE THREAD

**Issue by ZED63** [louisnw01/lightweight-charts-python#492]
### Question

i don't know why i'm having a hard time while trying to add a vertical span to my chart, not sure if i missed something or it's a bug (win11pro/python3.10/lightweight-charts 2.1)

here's the error i'm getting :

(py310) PS C:\Users\zed\Desktop\new_project> python .\tv.py
Exception in thread Thread-2 (loop):
Traceback (most recent call last):
  File "C:\Users\zed\.conda\envs\py310\lib\site-packages\lightweight_charts\chart.py", line 89, in loop
    window.evaluate_js(arg)
  File "C:\Users\zed\.conda\envs\py310\lib\site-packages\webview\window.py", line 48, in wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\zed\.conda\envs\py310\lib\site-packages\webview\window.py", line 459, in evaluate_js
    raise JavascriptException(result)
webview.errors.JavascriptException: {'name': 'ReferenceError', 'stack': 'ReferenceError: calculateTrendLine is not defined\n    at eval (eval at <anonymous> (:4:29), <anonymous>:7019:29)\n    at <anonymous>:4:29', 'message': 'calculateTrendLine is not defined'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zed\.conda\envs\py310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\zed\.conda\envs\py310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\zed\.conda\envs\py310\lib\site-packages\lightweight_charts\chart.py", line 94, in loop
    raise JavascriptException(f"\n\nscript -> '{arg}',\nerror -> {msg['name']}[{msg['line']}:{msg['column']}]\n{msg['message']}")
KeyError: 'line'

### Code example

```python
import pandas as pd
from lightweight_charts import Chart


if __name__ == '__main__':
        chart = Chart(inner_width=0.5, inner_height=0.5)
        chart.set(pd.read_csv('bar_data/EURUSD_30min.csv'))
        chart.vertical_span(start_time="2024-12-04 22:00:00",end_time="2024-12-05 22:00:00")

        chart.show(block=True)
```

**Comment by NikolayNelubov** [comment]
Check if you have the latest versions of providers renderer installed for your platform. Here is a link for more information --> [Web engine](https://pywebview.flowrl.com/guide/web_engine.html) For Windows platform, you need installed above >.NET Framework 4.6.2 and Edge WebView2 Runtime.

**Comment by debegr92** [comment]
I have the exact same error. I am **able to add vertical lines** (spans without end time), **but not spans** to mark after market session.

**working**

```pyhon
chart.vertical_span(span.start, color='rgba(255,255,255,0.5)')
```

**not working**

```pyhon
chart.vertical_span(span.start, span.end, color='rgba(255,255,255,0.5)')
```

**Comment by liuzhuanxingyun** [comment]
Yes, I also encountered this error. span.end cannot be used normally. My solution was to pass a list/tuple and render it piece by piece to achieve a similar effect.

<img width="1004" height="524" alt="Image" src="https://github.com/user-attachments/assets/41d276d0-d57e-4f31-8e8f-d09349f69a1f" />

**Comment by maxko37** [comment]
Is there any update on this except the workaround @liuzhuanxingyun referred to?

**Comment by liuzhuanxingyun** [comment]
Unfortunately I still don’t have any better progress on this issue either.  
For now I’m facing the same limitation.

**Comment by NikolayNelubov** [comment]
liuzhuanxingyun, maxko37 --> my best advice to you is to switch to - **bokeh**. It works great in real time with large amounts of data. It scales easily and handles streams well. I used **lightweight** for a long time, but the package was updated less and less frequently, and its functionality was very limited.  Here's a photo of my app in bokeh mode. And it all loads in real time use API bybit. 

![Image](https://github.com/user-attachments/assets/26c8cc9e-99c7-47f5-a13f-0c07dbdf419f)

**Comment by debegr92** [comment]
@NikolayNelubov do you have reference project to show how to use Bokeh and streaming candle data?

**Comment by NikolayNelubov** [comment]
@debegr92 sorry, i can't show you the full program. But i can show you the code for non-blocking download of candlestick data in real time from the Bybit exchange and optimal view visualization. This is a template. If the code is complex, then use Gemini, Clode, or ChatGPT for assistance. Just indicate which version of **Bokeh** you're using, this will reduce errors. 

[example bokeh.py](https://github.com/user-attachments/files/23964038/example.bokeh.py)
