### ISSUE TITLE
[BUG] 'NavigationAction' object has no attribute 'get_frame_name' and AttributeError: 'WebView' object has no attribute 'evaluate_javascript'

### ISSUE THREAD

**Issue by Martinpanzy** [louisnw01/lightweight-charts-python#493]
### Expected Behavior

```python
from lightweight_charts import Chart
chart = Chart(toolbox=True, width=1000, inner_width=0.6, inner_height=1)
chart.show(block=True)
``` 
AttributeError occur

### Current Behaviour

Traceback (most recent call last):
  File "/home/workspace/venv/lib/python3.8/site-packages/webview/platforms/gtk.py", line 340, in on_navigation
    if decision.get_navigation_action().get_frame_name() == '_blank':
AttributeError: 'NavigationAction' object has no attribute 'get_frame_name'
Traceback (most recent call last):
  File "/home/workspace/venv/lib/python3.8/site-packages/webview/platforms/gtk.py", line 597, in create_bridge
    self.webview.evaluate_javascript(
AttributeError: 'WebView' object has no attribute 'evaluate_javascript'

### Reproducible Example

```python
from lightweight_charts import Chart
chart = Chart(toolbox=True, width=1000, inner_width=0.6, inner_height=1)
chart.show(block=True)
```

### Environment

```markdown
- OS: ubuntu 20.04
- Library: 
  - pywebview 5.3.2
  - lightweight-charts 2.1
```

**Comment by Martinpanzy** [comment]
change the line71 in chart.py from 
```python
webview.start(debug=arg, func=self.loop)
``` 
to 
```python
webview.start(debug=arg, func=self.loop, gui="qt")
``` 
solved the issue.
