### ISSUE TITLE
Unable to run the example script

### ISSUE THREAD

**Issue by meta-ks** [louisnw01/lightweight-charts-python#72]
Hi, 
I create an new conda venv. [conda create -n tv_chart python=3.11.4 anaconda]
Then i did pip install lightweight-charts in the env. Everything working till this point.
Next i downloaded the 1_setting_data script. When i run it using python setting_data.py , i am getting this error:

[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/home/tc_chart/anaconda3/envs/tv_chart/lib/python3.11/site-packages/webview/guilib.py", line 25, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/tc_chart/anaconda3/envs/tv_chart/lib/python3.11/site-packages/webview/platforms/gtk.py", line 20, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QGLXContext: Failed to create dummy context
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
^[[A^[[A^CTraceback (most recent call last):
  File "/home/tc_chart/Desktop/Quant/viz/lightweight-charts-python/examples/1_setting_data/setting_data.py", line 11, in <module>
    chart.show(block=True)
  File "/home/tc_chart/anaconda3/envs/tv_chart/lib/python3.11/site-packages/lightweight_charts/chart.py", line 97, in show
    self._loaded.wait()
  File "/home/tc_chart/anaconda3/envs/tv_chart/lib/python3.11/multiprocessing/synchronize.py", line 349, in wait
    self._cond.wait(timeout)
  File "/home/tc_chart/anaconda3/envs/tv_chart/lib/python3.11/multiprocessing/synchronize.py", line 261, in wait
    return self._wait_semaphore.acquire(True, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

**Comment by louisnw01** [comment]
https://pywebview.flowrl.com/guide/installation.html#dependencies
